### PR TITLE
navbar links commit

### PR DESCRIPTION
**Pull request by SkandTiwari**
basic layout of navbar and links.

### CODE REVIEW

**Review by gurucoolasia — CHANGES_REQUESTED** [review]
Hi Skand please check with App.js. I think if the div is removed then you should enclose it within a fragment and also check the responsiveness of the Navbar on multiple devices. And push the changes and request for the pull then i will address it.

**Comment by SkandTiwari** [comment]
good evening sir, i have checked the responsiveness to and tried to improve it, we will make it better after adding the logo and logout button.

**Review by gurucoolasia — CHANGES_REQUESTED** [review]
Hi Skand I just cloned your project and checked on my system. The Navbar looks good on normal screen but i will request you to put the nav-links inside the hamburger menu when the screen-size decreases to mobile size.

**Comment by SkandTiwari** [comment]
Hello sir, I was thinking of the same, but once Rohan finishes the logo and
log out button part, i will put the hamburger menu. It will be easier for
me to figure out the right position for it as well as the orientation of
the drop-down menu then.

Thanks for the advice.

**Pull request closed without merging**
